### ISSUE TITLE
Yanked releases on PyPI for 2.* releases

### ISSUE THREAD

**Issue by m-rossi** [conda-forge/reedsolo-feedstock#16]
### Comment:

@lrq3000 I just noticed as #15 got started and I was searching for notes about issues on Python 3.12 that you yanked all releases for version 2.*. What do you think, should I also [remove the conda-packages](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages)?

**Comment by ocefpaf** [comment]
> ### Comment:
> @lrq3000 I just noticed as #15 got started and I was searching for notes about issues on Python 3.12 that you yanked all releases for version 2.*. What do you think, should I also [remove the conda-packages](https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages)?

If upstream yanked we should mark them as broken here too,

**Comment by m-rossi** [comment]
Ok, I will take care of that.
